version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: eventapi-conteiner
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5431:5432"
    restart: always